### ISSUE TITLE
Investigate making an "Ember" provider

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/grid-intensity-go#11]
Ember published annual datasets of carbon intensity of electricity, based on their own analysis.

These are like the IEA, but much more liberally licensed, meaning it's much easier to bundle them into software.

Ember are an NGO listed below:

https://ember-climate.org/

And they have an annual report like this:

https://ember-climate.org/

With this permissively licensed data:
https://ember-climate.org/global-electricity-review-2021/data-explorer/

They also explain their methodology here in detail for each country they list:
https://ember-climate.org/global-electricity-review-2021/methodology/

**Comment by rossf7** [comment]
@mrchrisadams I'm going to close this as #38 covers adding monthly data from Ember. 

I moved #38 from the grid-intensity-exporter issue yesterday.
