### ISSUE TITLE
Prompting for country on first run

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/grid-intensity-go#16]
After using the new CLI, I've realised that lots of us might have a locale like the US even if we live somewhere else (this was my experience the first time when testing it in Berlin).

If you know your country code you can still pass in the cli flag so it's not a massive problem, but it did catch me out.

Anyway - if we already get some kind of support of config files from the suite of CLI tools we use, it might be worth prompting for a given country on the first run, and then writing this to something like `~/.config/grid-intensity`.

Not a priority, but would be nice.

**Comment by rossf7** [comment]
Good point and I can see lots of situations when the locale won't match. Right now I'm in the UK but my locale is set to ES 😄 

We could prompt the user on first run. Maybe still defaulting it from the locale but letting the user change it? Persisting this to a config file would be useful and can be done with the viper library.

https://github.com/spf13/viper

**Comment by rossf7** [comment]
This shipped in the 0.3.0 release
