### ISSUE TITLE
CLI Proposal

### ISSUE THREAD

**Issue by ofpiyush** [thegreenwebfoundation/grid-intensity-go#3]
This issue outlines the minimal CLI we want to implement for the first release of the golang grid-intensity CLI.

(_See #6 for the earlier CLI proposal ideas from @ofpiyush_)

```shell
grid-intensity
```

This returns back something like the response below:

```json
{
 "locale": "nl",
 "country_name": "Netherlands",
 "country_code_iso_2": "NL",
 "country_code_iso_3": "NLD",
 "carbon_intensity_type": "avg",
 "carbon_intensity": 388.186,
 "generation_from_fossil": 69.84,
}
```

The local might be more detailed this, and we probably need to figure out the mapping from local to country iso code.

### How we get the location

We try to infer the location based on the current locale. We offer override with flags or a similar process (@rossf7  I'm happy to defer to you)
Library to get the current locale on Windows, Mac and Linux
https://github.com/Xuanwo/go-locale

We allow the overriding of inferred location by passing in a ISO country code as a flag

### Presenting carbon intensity

By default, we show the **average** carbon intensity for the given location, based on a local dataset included in the binary, from Ember.

We already have some of this information in this PR 69 of the admin portal repo
https://github.com/thegreenwebfoundation/co2.js/pull/69

https://github.com/thegreenwebfoundation/co2.js/blob/26a5c8722171bbead47f2e6588ec7f11cc66bf96/data/intensity-by-country.json

Once we have access to providing marginal intensity we offer that as well. @rossf7 - in this case here, I'm not sure what the API ought to look like for this. Given that marginal is less well known, I'm inclined to just default to average as we definitely have access to it.

###

**Comment by mrchrisadams** [comment]
Coming back to this.

The Green Software Foundation has been working on a carbon aware SDK, which is conceptually very similar to what we were working on here.

Look at the API defined for their CLI:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md

If it's simple to call go binaries from python (and I guess it should be), we could conceivably adapt something at the Golang level, to support this issue:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/27

This is the approach that ESbuild uses to provide a really fast, nice to use alternative to webpack, rollup, parcel and the rest.

https://esbuild.github.io/

Implementing the CLI here means we could conceivably have a nice reusable core in Go-lang, that using the same wrapping-a-go-binary-trick as ESBuild gets consumed in:

- any node app (cloud carbon footprint, sitepeed.io, our own co2.js tools)
- any go app (kubernetes, nomad, grafana stack, etc.)
- any python app that can call go binaries quickly

**Comment by mrchrisadams** [comment]
Hey @rossf7, for the CLI issue, we can either add the sample info here, or I can create a new issue with the invocations we described on the all here.

Which would you prefer I do?

**Comment by rossf7** [comment]
Hey @mrchrisadams I'm fine with continuing here. Can you add the extra sample info?

**Comment by rossf7** [comment]
First release of the CLI with the Ember data has shipped

See https://github.com/thegreenwebfoundation/grid-intensity-go/releases/tag/v0.1.0
