### ISSUE TITLE
Add a prometheus exporter

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/grid-intensity-go#4]
If we're targetting schedulers like Kubernetes and Nomad, as @rossf7 suggested one of the nicest ways to make it possible for a scheduler to take the carbon-intensity of compute into account would be to expose the information in a form that prometheus, one of the default monitoring tools in opsland, can use.

Ross's suggestion of creating an exporter makes a lot of sense, as it would largely entail use making a few time series that would expose stuff like:

- carbon intensity for last 30 mins, as a high, medium, low figure (we'd likely need to figure these out on a per region basis if they're not exposed by the API)
- if it's exposed, some derived figure for the carbon intensity over the next N hrs or so, just at the high/medium/low figures
  - 30mins
  - 1hr
  - 3hrs
  - 6hrs
  - 12hrs
  - 24hrs

_(if we can expose the actual numbers that would be useful, but it really depends on the licensing of the data we use)_

### Why this would help

Exposing these metrics would allow us to somewhat mimic the way day-ahead figures for electricity work, and if we tracked them like this, we'd have actionable measurements for a scheduler to figure out when or where to place work based on an estimate the carbon intensity.

For example, if you knew a job took 3hrs, and carbon intensity was low in one of your DC's but high in another one, you'you might shunt it to the greener one, while energy is green.

Conversely, if you knew that intensity was high right now, but dropping later, you'd be able to see that the average intensity was lower over the longer period, you might schedule it to run after the peak.

Similarly, if we're capturing the time series you can work out a running total of something like the _social cost of compute_, - total up the CO2 emitted, and add a multiplier to account for the cost of carbon. 

This cost multiplier is likely to something changes from org to org, so but it's likely something that would be useful to expose for management.

### Implementing it

From what I can see, Prometheus works by collecting metrics from nodes it monitors that are running clients.

These clients expose metrics over a web interface at a specific port, as a data structure I haven't quite figured out yet. If we can figure out the datastructure, the client will take care of the serving part for us, and be relatively easy to add to any k8s or nomad cluster.

@rossf7 I think this is something you have some experience with I think, so I think I should defer to you here 👍 

### Useful links

More on exporters - https://prometheus.io/docs/instrumenting/exporters/
Client libs we might use - https://prometheus.io/docs/instrumenting/clientlibs/
The metric types are very similar to ones used by grafana and statsd -  https://prometheus.io/docs/concepts/metric_types/

**Comment by rossf7** [comment]
Hey @mrchrisadams, I had a go at the exporter in #6. It exposes a metric for the current carbon intensity. 

I think the exporter can help with when to run workloads. e.g. Only run if the current or forecast carbon intensity is below a threshold. Or scale up faster when the carbon intensity is lower.

I don't think it can help with where to run workloads. For both Nomad and Kubernetes I think a separate autoscaler controller is needed for that.

## Metrics

```
curl -s http://localhost:8000/metrics | grep grid_intensity
# HELP grid_intensity_carbon_actual Actual carbon intensity for the electricity grid in this region.
# TYPE grid_intensity_carbon_actual gauge
grid_intensity_carbon_actual{provider="carbonintensity.org.uk",region="UK"} 157
```

For designing the Prometheus metrics I looked at both gauges and histograms but I think a gauge is a better fit. For the forecast I think the exporter could expose multiple metrics. Users of the exporter can then choose the metric that best fits their needs.

So as well as `grid_intensity_carbon_actual` there could be `grid_intensity_carbon_next_1h`, `grid_intensity_carbon_next_12h`, etc.

WDYT?

**Comment by mrchrisadams** [comment]
Hi Ross,

Thanks for this!


If you were to do this with Nomad, I you'd apply these the constraints about carbon intensity to the job you want to run, rather than the nodes doing the work. 

From what i can see, Nomad has the notion of constraints, which can be applied to jobs, which have their own 
_groups_, and within those groups, you can have tasks. you can see the hierarchy below, and you can see how the constraints can be applied at basically every level. If there are no nodes that meet the criteria, the job doesn't run, so presumably you could have a constraint that basically said:

> run this job, but only on client nodes with a carbon intensity of less than 300 grams of CO2 per kWh

I think it would wait til the conditions were met, and _then_ schedule the work. If you have the history from prometheus, presumably you could even tie this to the previously recorded carbon intensity in a datacentre.

```
job "docs" {
  # All tasks in this job must run on linux.
  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "example" {
    # All groups in this job should be scheduled on different hosts.
    constraint {
      operator  = "distinct_hosts"
      value     = "true"
    }

    task "server" {
      # All tasks must run where "my_custom_value" is greater than 3.
      constraint {
        attribute = "${meta.my_custom_value}"
        operator  = ">"
        value     = "3"
      }
    }
  }
}
```

I think this is a bit like how you might attach metadata to k8s workloads, so they run in various places, or take into account various factors. This piece here shows how some folks at microsoft started implementing the ideas from Aled James and Daniel Schien's paper a Low Carbon Kubernetes scheduler:

https://devblogs.microsoft.com/sustainable-software/carbon-aware-kubernetes/

If we wanted to embed some of the science around climate into this, we might even have something like a notion of _social cost of compute_, which might be something like the CO2 per kilowatt hour, multiplied by a figure based on the social cost of carbon. 

This approach of pricing carbon emission makes it a thing you might optimise for, and there's precedent with groups like the New Climate institute and their 'climate responsibility' concept:

> …we apply a price per unit of emissions, to the GHG emissions that we determine in (from our activity).
>
> We determine the price level based on the best available scientific evidence on the carbon price signal required for alignment with the Paris Agreement objectives. We review this price level each year in the light of new evidence.
NewClimate Institute’s determination of the price level for its Climate Responsibility approach is informed by the carbon price signal required to put the transformation of the global economy on a pathway compatible with the Paris Agreement temperature objectives.
>
> The High-Level Commission on Carbon Prices surveyed the available scientific literature, concluding that the explicit carbon-price level consistent with the Paris Agreement temperature objectives is at least US$40–80/tCO2 by 2020, provided that a supportive policy environment is in place (High-Level Commission on Carbon Prices, 2017). Informed by this report and allowing for its uncertainties, NewClimate Institute has imposed a price level of EUR 100/tCO2e for the 2014-2019 period. This is also in-line with the central estimate of climate change avoidance costs over the period to 2030 used in the European Commission’s 2019 Handbook on the External Costs of Transport (European Commission, 2019).

For example if we know a job will will run for 2000 compute hours, and result in 2000 kilowatt hours of energy being used, at 500 g of CO2 per kilowat hour, we'd end up with a tonne of CO2 being emitted.

We might surface that in the metrics somehow, as an actual cost figure in EUR or GPD or USD, to make it clearer what we're optimising for.

Microsoft basically do this already [with their internal carbon fee][1], albeit at a lower level of 15 USD per tonne, and [Swiss Re have announced they're applying an internal levy of 100 EUR per tonne rising to 200 EUR per tonne too][2] for their operations.



[1]: https://blogs.microsoft.com/on-the-issues/2019/04/15/were-increasing-our-carbon-fee-as-we-double-down-on-sustainability/
[2]: https://twitter.com/BrigitteKnopf/status/1319487176451776513

**Comment by mrchrisadams** [comment]
I really appreciate you putting the time in to thinking about the naming conventions, and ways you'd surface this in grafana:

> So as well as grid_intensity_carbon_actual there could be grid_intensity_carbon_next_1h, grid_intensity_carbon_next_12h, etc.

Yes, I think this is a good approach to take. I've learnt from @ofpiyush's experimenting that forecast figures are less common that we thought, so it might be worth extracting the forecast metrics into a separate issue, and seeing if we can ask some people with more domain expertise in the energy sector to see how hard this data is to find.

But naming convention you have so far? Sounds good 👍

**Comment by rossf7** [comment]
I'm not sure if constraints can be used for this. Usually they are related to characteristics of the nodes. Like the amount of RAM or whether they have GPU.

I think you can have custom metadata for the nodes. But it would need the autoscaler component to query Prometheus and set the node metadata.

Another approach is to use the Prometheus APM plugin. https://www.nomadproject.io/docs/autoscaling/plugins/apm#prometheus-apm-plugin This looks very similar to Kubernetes. The autoscaler runs a query in PromQL and sets the number of containers that should be run.

In Kubernetes this is called a Horizonal Pod Autoscaler and these also support custom metrics from Prometheus. These are useful for setting how many containers to run based on metrics.

But a custom autoscaler provides more control. For example on Nomad if its a multi region cluster you still need the target autoscaler to move the task to a specific region. I don't think the Prometheus APM plugin can do that.

**Comment by rossf7** [comment]
On the data structure for the forecast. Yes that is tricky and I'm now not sure my first approach is correct. Maybe it should just be a forecast metric with the period as a label. In the query you can then choose the value you want via its label.

```
grid_intensity_carbon_forecast{period="1h",provider="carbonintensity.org.uk",region="UK"} 163
grid_intensity_carbon_forecast{period="24h",provider="carbonintensity.org.uk",region="UK"} 157
```

Aligning the APIs across providers of the data is going to be hard and like you say forecast data is more complex. Good idea to talk to some people working in this field.

Including the social cost of compute is an interesting idea and the exporter could emit this as well as carbon intensity. This has got me into the topic! So looking forward to discussing more this week.

**Comment by mrchrisadams** [comment]
@rossf7  I've created an issue to refer to this in the new `grid-intensity-exporter` repo:

https://github.com/thegreenwebfoundation/grid-intensity-exporter/issues/1

**Comment by rossf7** [comment]
@mrchrisadams Perfect thanks. I'll open a new PR later and link to the new issue.

**Comment by mrchrisadams** [comment]
Hey @rossf7, I'm closing issue as we've had a release of the grid carbon carbon intensity explorer available for aaaages now.

https://github.com/thegreenwebfoundation/grid-intensity-exporter/

However, your hints for the Nomad plugin have given me an idea for how we can actually extend the nomad scheduler to be carbon aware.

I'll update the thegreenwebfoundation/grid-intensity-exporter#1 with how I think it can work.
