### ISSUE TITLE
Simplify provider names

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/grid-intensity-go#45]
Currently provider names are a bit verbose (e.g. `--provider=carbonintensity.org.uk`). For those getting started, this could take a bit getting used to, and would be easier to forget.

Shorter, more memorable, provider names would lead to a slightly nicer developer experience.

**Comment by rossf7** [comment]
Thanks @fershad this is great feedback. I went with the domains as they are unique but you're right they are hard to remember / work with.

What about using these names instead?

- CarbonIntensityOrgUK
- ElectricityMap
- Ember
- WattTime

We could also add a `grid-intensity provider list` command that outputs all the supported providers. I think that would be useful as we add more providers. WDYT?

**Comment by fershad** [comment]
Thanks @rossf7. These look good.
Having the `grid-intensity provider list` command will be very handy for exposing these. It'll help with the onboarding docs as well, since we'd be able to tell people to run the command, rather than having to go through a list of providers on the docs site.

**Comment by rossf7** [comment]
Thanks @fershad I'm adding the provider names as part of the refactoring in #44 and then I'll add the provider list command.

**Comment by fershad** [comment]
Thanks Ross. Can you tag me in the PR when that's ready. I'll start updating the docs then.

**Comment by rossf7** [comment]
@fershad Will do but the refactoring will take a couple of PRs. 

So I'll do the updating of the provider names in a separate PR. Rather than mixing the formats. I'll tag you in that PR.

**Comment by rossf7** [comment]
Changes are merged and will go in the next release.
