### ISSUE TITLE
Set default region for providers

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/grid-intensity-go#48]
When using providers that only support one region (e.g. CarbonIntensity.org.uk), it would be nice to be able to omit the `--region` flag when running the `grid-intensity` command.

As a bonus, having a default region set for providers would also make it easier for people to get started with/try out other providers. Rather than having to find a list of regions for WattTime, I could try it with the default to see what kind of data is returned.

**Comment by fershad** [comment]
>When using providers that only support one region (e.g. CarbonIntensity.org.uk), it would be nice to be able to omit the `--region` flag when running the `grid-intensity` command.

Scrap this. I realised that this is already implemented.

**Comment by mrchrisadams** [comment]
👍
