### ISSUE TITLE
Refactor prometheus metric labels for carbon aware scheduling

### ISSUE THREAD

**Issue by rossf7** [thegreenwebfoundation/grid-intensity-go#59]
While researching a blog post on carbon aware scheduling I noticed a problem with our current prometheus metrics.

Currently we have a region label with the value needed by the data provider. e.g. the DE country code for WattTime in this example

```
grid_intensity_carbon_relative{provider="WattTime",region=”DE”,units="percent"} 64
```

However to do carbon aware scheduling you need to know either the hostname of the server or the region specified by the hosting provider.

This is named Region in the Nomad Job and Agent APIs. For Kubernetes usually nodes are labelled with the standard label `topology.kubernetes.io/region`

So we will

- Rename Region to Location for the identifier needed by the data provider.
- Add a new label named Region for the identifier used by the scheduler.
- Add a new label named Host to identify the node where the exporter is running.

```
grid_intensity_carbon_relative{provider="WattTime",location="DE",region=”eu-central-1”,host=”worker-1”,units="percent"} 64
```

**Comment by fershad** [comment]
@rossf7 if I'm reading this correctly, this change would mean that going forward the `--region` flag in the CLI would be replaced with `--location`, right?

So using the CLI would look like:

```
grid-intensity --provider=Ember --location=PT
```

**Comment by fershad** [comment]
Thanks @rossf7. Got the changes for the docs in staging over at https://github.com/thegreenwebfoundation/developer-docs/pull/11#issuecomment-1233667136

**Comment by rossf7** [comment]
@mrchrisadams @fershad I think this is done. Can we close?

**Comment by mrchrisadams** [comment]
Closing as requested 👍
