### ISSUE TITLE
Add CO2 Signal as provider

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/grid-intensity-go#65]
ElectricityMaps offers a free API call [CO2signal](https://www.co2signal.com/). The API provides access to the latest carbon intensity data (at a country level). Since it is free, having this integration would make Grid Intensity Go a viable option for developers to use in hackathons, demo projects, prototypes and the like. 

The API requires an API key for access, and is rate limited to 30 requests per hour/1 per second.

API docs can be found at: https://docs.co2signal.com/

**Comment by mrchrisadams** [comment]
hi @rossf7 ! That makes a lot of sense - I think this is a good idea. I'll respond in #71 with any comments there.

**Comment by mrchrisadams** [comment]
We should also probably close this, or make a new issue for supporting the endpoints.

**Comment by rossf7** [comment]
Thanks Chris <3 closing in favour of #72
