### ISSUE TITLE
Support Electricity Maps free tier

### ISSUE THREAD

**Issue by rossf7** [thegreenwebfoundation/grid-intensity-go#72]
Electricity Maps announced their new free tier last week https://www.electricitymaps.com/news/our-free-api-is-now-available-among-our-other-products

We can support this by making the API URL configurable for the Electricity Maps provider. There are 3 types of base URL we need to support 

- Free tier `https://api-access.electricitymaps.com/free-tier/`
- Paid self service users including free trial users e.g. `https://api-access.electricitymaps.com/2w97h07rvxvuaa1g/`
- Larger users that don't use their API portal `https://api.electricitymap.org/v3`

Maybe we should also change the default URL to the free tier?
Currently the default is `https://api.electricitymap.org/v3`

This supersedes #65 which was to add [CO2signal](https://www.co2signal.com/) as a provider which serves the same data but on a different domain.

**Comment by rossf7** [comment]
Hi @mrchrisadams @fershad 
this was added in #71 and released in v0.5.0

I did a docs PR https://github.com/thegreenwebfoundation/developer-docs/pull/25 

Once that's merged I think we can close this?

**Comment by mrchrisadams** [comment]
Thanks @rossf7 , there's one tiny change I've requested in the docs, then I think this is good to close. Thanks again :)

**Comment by fershad** [comment]
Docs site is updated, https://developers.thegreenwebfoundation.org/grid-intensity-cli/explainer/providers/#electricity-maps-api-token-required. I reckon this is good to close.
