### ISSUE TITLE
Should we rename provider to ElectricityMaps and make free tier the default URL?

### ISSUE THREAD

**Issue by rossf7** [thegreenwebfoundation/grid-intensity-go#77]
For the provider name we use the singular `ElectricityMap` and not the plural `ElectricityMaps`. This is because we implemented before ElectricityMaps rebranded.

I think it would be clearer if we renamed the provider and the code. WDYT?

Also as I mentioned in #72 should we change the default URL from `https://api.electricitymap.org/v3` to `https://api-access.electricitymaps.com/free-tier/` ?

I think most new users will be using either the free tier or the 30 day free trial and not `https://api.electricitymap.org/v3`.

These are both breaking changes but the library is still 0.X and we can list them as breaking in the changelog.

@mrchrisadams WDYT?

**Comment by mrchrisadams** [comment]
Hi @rossf7  - I totally thought that emoji was mine and that I had responded! Apologies for the slow response.

This feels like a really nice good first issue, as it would improve the DX, but not involve too much new work.

I've added that label accordingly.

**Comment by mrchrisadams** [comment]
Hey @rossf7 - coming back to this after chatting on Zulip.

I just got bit by the same `https://api-access.electricitymaps.com/free-tier/` versus `https://api-access.electricitymaps.com/free-tier` issue we saw, and I think this is a good idea.
